### PR TITLE
handle ErrorKind::Interrupted in try_nb!

### LINKED ISSUE #37: EINTR handling
I wanted to bring `EINTR` (`ErrorKind::Interrupted`) handling up as a general topic.

Traditionally, `EINTR` on Unix systems has meant that a signal has interrupted this syscall. Usually, the operation can be immediately retried (unlike `EAGAIN`/`EWOULDBLOCK`/`WouldBlock` which would have to be retried later).

How should `tokio-io` handle `EINTR`, if at all? For example, [this call](https://github.com/tokio-rs/tokio-io/blob/d48c506a3edd13bc5b0bfa5e49bb53021d37c07c/src/framed_write.rs#L201) in `FramedWrite::poll_complete` can fail with `ErrorKind::Interrupted` -- this means that a stream forwarding to a `FramedWrite` can fail with `EINTR` at [this point](http://alexcrichton.com/futures-rs/src/futures/stream/forward.rs.html#80). This means that a `Forward` future when run with `Core::run` will fail and consume the stream and sink, even though it can just be immediately retried.

* Should `FramedWrite` retry on `ErrorKind::Interrupted`?
* Should `try_nb!` retry on `ErrorKind::Interrupted`?

More general questions (perhaps more appropriate for other crates):

* Should `Forward` futures have some way to return the stream and sink on error as well?
* How should this general pattern (`Core::run` gets passed a future which errored out, but the future is still valid and `poll` can still be called on it) be handled?

### PR DESCRIPTION
**Pull request by sid0**
As discussed in #37, `tokio-io` must handle `ErrorKind::Interrupted` errors at
some level. `try_nb!` neatly solves this problem for all consumers, both
internal and external, and prevents this class of bugs from being made.

This loop would be much cleaner with the loop-break-value feature
(https://github.com/rust-lang/rfcs/pull/1624), but that is still experimental.

Closes #37.

(I put this up to initiate debate -- this isn't necessarily how the final feature should look :) )

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I fear though that this is a pretty weighty implementation for an otherwise should-be-concise macro. My preference would be to move EINTR handling elsewhere. I see two possible options for us:

* Squelch EINTR in the primitives, e.g. TcpStream/UdpSocket/etc. This is not what the standard library does, but means that no one ever has to deal with EINTR.
* Handle EINTR in combinators and document that it can arise. This is what the standard library does but the combinators are likely used less than, for example, libstd's `write_all` function, so this may not be as effective.

I was personally persuaded by @carllerche's argument that tokio is enough of a "runtime" that I think it's ok to expect it to handle EINTR internally. In that sense I'd be more in favor of squashing this at the tokio-core layer, retrying on EINTR in TcpStream and friends.

**Comment by alexcrichton** [comment]
Hm true yeah, but my thinking is that this is too surprising for a macro because of the `loop` itself. That means that each iteration of the loop will reevaluate `$e`. This not only has dynamic implications but also has compiler implications (you can't move variables inside now). For example these will both produce surprising results:

```rust
// side effects twice
try_nb!(self.foo(self.something_with_side_effect()));

// compile error
try_nb!(self.foo(some_string));
```

@sid0 do you think we *shouldn't* nip the errors in the bud here at the source? If we did that do you think we'd still need handling of EINTR elsewhere?

**Comment by sid0** [comment]
Hmm, that's a good point. Sorry, still a bit of a noob with Rust :)

What if we just documented that anything that implements AsyncRead or
AsyncWrite must never return EINTR. We already impose a few constraints
compared to plain old Read and Write (like being async, and not using
write_all). I think as long as we document that as a constraint people will
be fine with implementing it.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Pull request closed without merging**
