### PR TITLE
Fix netty style length_delimited decoder

### PR DESCRIPTION
**Pull request by yorkart**
Fix netty style decoder. The parameter `num_skip` and `length_adjustment` meaning inconsistency

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks. Could you provide an overview of what this PR is providing?

**Comment by yorkart** [comment]
frame:
```
|msgId(4bytes) | type(1bytes) | bodyLength(4bytes)  | body...|
```
decode with:
```rust
Builder::new()
        .length_field_length(4)
        .length_field_offset(5)
        .num_skip(0)
        .length_adjustment(0)
```
I want to get all frame's data(header and body), but it doesn't work .
Is the parameter `num_skip` and `length_adjustment` meaning different from that of netty's `LengthFieldBasedFrameDecoder`?
Does the `num_skip` correspond to the `initialBytesToStrip` of `LengthFieldBasedFrameDecoder` ?

**Comment by carllerche** [comment]
I think I see the issue, there is a bit of a disconnect around terminology maybe:

`num_skip`'s documentation states:

> Sets the number of bytes to skip before reading the payload

This implies that the decoder skips that number of bytes then starts reading the payload. So, the payload will be the range of data starting at `num_skip` and including the payload data.

`length_adjustment` adjusts the payload size according to the value.

I believe this is what the code currently does.

I guess `num_skip` is similar to `initialBytesToStrip`, but means something slightly different. Here, it tells the decoder how to find the start of the payload.

**Comment by carllerche** [comment]
The tokio-io crate has been moved into the [tokio](https://github.com/tokio-rs/tokio) git repo.

This PR has been inactive, so I am just going to close it.

**Pull request closed without merging**
