### PR TITLE
Add framed_read and framed_write methods

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by carllerche** [comment]
Could you elaborate more about why you would like to expose these at the trait level? They were explicitly omitted to avoid crowding the trait.

**Comment by cramertj** [comment]
Ah, I didn't realize they were intentionally omitted.

Personally, I think that methods are much more discoverable and convenient than the separate `new` functions.

Discoverable: when reading the rustdoc for a type outside of tokio-io that implements AsyncRead, users will only see the `framed` method, which they might not be able to call since the type might not implement `AsyncWrite`. If the type only implements `AsyncWrite`, there won't be any mentioned of `framed` at all. In order to get what they want, they'll have to know to go digging around in tokio-io for the `FramedRead` and `FramedWrite` types.

Convenience: `FramedRead` and `FramedWrite` require extra imports, and IMO `FramedRead::new(foo.bar().baz(), Bytes).map(...)` is harder to read than `foo.bar().baz().framed_read(Bytes).map(...)`.

**Comment by carllerche** [comment]
One has to balance having the fn available vs. clutter. Otherwise, we'd have everything in a single namespace and glob import it all :)

the `framed` docs could point to the specialty constructors. to aid in discoverability.

**Comment by cramertj** [comment]
> One has to balance having the fn available vs. clutter. Otherwise, we'd have everything in a single namespace and glob import it all :)

Sure, but I think that seems like a bit of hyperbole, especially in this particular case. These traits already have very few methods (especially in comparison with `Future`/`Stream`/`Sink` et. al), and these are important ones to point out. Wanting to use an IO object for only reading or writing at a particular time is an eminently reasonable and common thing to do.

**Comment by carllerche** [comment]
I personally prefer erring on the side of being conservative. I think we should start with a section in the `framed(...)` docs indicating that for unidirectional framing, use the `new` constructors directly.

**Comment by cramertj** [comment]
Okay, I'll open a new PR adding docs.

**Comment by carllerche** [comment]
Closing as the decision was to not add these fns.

**Pull request closed without merging**
