### PR TITLE
SyncRead, SyncWrite types

### PR DESCRIPTION
**Pull request by stepancheg**
These types implement `AsyncRead` and `AsyncWrite` synchronously.
They don't follow `AsyncXxx` protocol.

These types are useful in tests. You may have async logic (e.  g.
read a frame from `AsyncRead` passed by value), and you want to
execute it with provided `&mut Read` (e. g. if you work with
synchronous socket in the test).

In my particular use case I have HTTP/2 server which is implemented
using tokio. And I have mock HTTP/2 client, which is a simple socket
wrapper with functions like `write_frame` and `read_frame`.  With
`SyncRead` and `SyncWrite` types I can reuse frame serialize/parse
logic in synchronous test code.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems sort of odd to me to have in the tokio-io crate itself because there's basically no way to verify that the sematnics of `Async{Read,Write}` are adhered to? This seems great for like a "utilities" crate but perhaps not in the core itself

**Comment by stepancheg** [comment]
> there's basically no way to verify that the sematnics of Async{Read,Write} are adhered to

Probably struct should be called something like `SyncReadIKnowWhatIAmDoing` or `SyncReadUnsafe`.

> This seems great for like a "utilities" crate but perhaps not in the core itself

It took from me a couple of weeks to understand how to execute async code with `&mut Read` (before that sync version was a copy-paste of async version), so I though I should share the knowledge with the library. Anyway, I have implemented this trivial code [in my library](https://github.com/stepancheg/rust-http2/blob/1d9804fa3170f3a55581d172903d96f26db536e1/src/solicit_async.rs#L75-L89), so if there's no place in tokio-io for code like that, it's not a big deal.

**Comment by alexcrichton** [comment]
@carllerche do you have thoughts for this? Do you feel like it may belong in tokio-io?

**Comment by carllerche** [comment]
I could see how something like this *could* be useful in tokio-io. However, the cost of having it is another type that newcomers have to see when exploring the docs.

I'm not sure about the naming, I don't think it should be `SyncRead`...

As for the implementation, I don't understand why it takes a ref? Also, the internals of the struct should be opaque IMO.

**Comment by stepancheg** [comment]
Not a big deal.

**Pull request closed without merging**
