### PR TITLE
use FrameTooBig type instead of strings for length_delimited errors

### PR DESCRIPTION
**Pull request by seanmonstar**
Currently, to detect if a frame was too big, something like this is required:

```rust
if let ErrorKind::InvalidData = err.kind() {
    if err.description() == "frame size too big" {
        // handle frame too big error
    }
}
```

This is quite fragile. Instead, this PR uses a specific type for the custom IO error, allowing kind like this:

```rust
if let ErrorKind::InvalidData = err.kind() {
    if err.get_ref().is::<tokio_io::length_delimited::FrameTooBig>() {
        // handle frame too big error
    }
}
```

- The `err.description()` and `err.to_string()` has been kept the same, so anyone currently relying on those will still work.
- While downcasting doesn't catch if `tokio_io` wouldn't return the specific type in the error, it can allow other things.
  - The message or description can be allowed to change, maybe included the lengths, and downcasting will still match it. 
  - If the type is being phased out, `#[deprecated]` can be used to alert people of what to change to. This doesn't help people who are using `err.description()`.
- This technically is breaking change for anyone specifically downcasting to a static str, but doing that is likely supremely rare.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems reasonable to me! Perhaps this struct could be mentioned in the documentation?

**Comment by seanmonstar** [comment]
@alexcrichton sure, how? Like, an example added to the `length_delimited` module docs?

**Comment by alexcrichton** [comment]
Maybe on the builder method that configures the maximum size?

**Comment by seanmonstar** [comment]
Added a sentence about the errors used on the `Builder.max_frame_length` method. Let me know if you had something else or more in mind.

**Pull request merged**
